export const environment = {
    production: true,
    t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-IPS:T-ETK:T-RAS:T-PPB:T-PET:T-MTS:T-TIL:T-DGF:T-NAT:T-HPB:F-TOW:T-KNB:T-BAN:T-AST:T-MON:T-CNT:T-AUT:T-WUN:T-INT:T-DPA:T-QIN:T-VAU:T-OVP:F',
    VERSION: require('../../package.json').version,
    botcredendialsURL: 'https://stage.eks.tiledesk.com/api/modules/dialogflow/botcredendials/', //'https://tiledesk-df-connector-prod.herokuapp.com/botcredendials/',
    rasaBotCredentialsURL: "https://tiledesk-rasa-connector-prod.herokuapp.com/botcredendials/",
    remoteConfig: false,
    WIDGET_BASE_URL: 'https://stage.eks.tiledesk.com/widget/',
    SERVER_BASE_URL: 'https://stage.eks.tiledesk.com/api/',
    CHAT_BASE_URL: 'https://stage.eks.tiledesk.com/chat/', // 'http://localhost:8102/', // 'https://console.tiledesk.com/v2/chat5-dev/', // 'http://console.tiledesk.com/v2/chat/', 
    testsiteBaseUrl: 'https://stage.eks.tiledesk.com/widget/assets/twp/index.html', // 'https://widget.tiledesk.com/v5-dev/assets/twp/index.html',
    wsUrl: "wss://stage.eks.tiledesk.com/api/", // 'wss://eu.rtmv3.tiledesk.com/',
    reCaptchaSiteKey: "6Lf1khcpAAAAABMNHJfnJm43vVTxFzXM7ADqDAp5",
    globalRemoteJSSrc: "https://www.google.com/recaptcha/api.js?render=6Lf1khcpAAAAABMNHJfnJm43vVTxFzXM7ADqDAp5, https://panel.tiledesk.com/v3/scripts/script.js,  https://panel.tiledesk.com/v3/scripts/segment_script.js, https://panel.tiledesk.com/v3/scripts/custom_script.js",
    firebaseAuth: false,
    uploadEngine: 'native',
    baseImageUrl: 'https://stage.eks.tiledesk.com/api/',
    fileUploadAccept: "image/*,.pdf,.txt",
    pushEngine: 'firebase',
    chatEngine: 'mqtt',
    logLevel: 'info',
    communityTemplatesUrl: "https://stage.eks.tiledesk.com/api/modules/templates/public/community", // "https://chatbot-templates-app-v3.herokuapp.com/chatbots/public/community",
    templatesUrl: "https://stage.eks.tiledesk.com/api/modules/templates/public/templates", // "https://chatbot-templates-app-v3.herokuapp.com/chatbots/public/templates",
    // appsUrl:"https://tiledesk-apps.herokuapp.com/",
    appsUrl: "https://stage.eks.tiledesk.com/api/modules/apps/",
    cdsBaseUrl: '/cds/', //'/v3/cds-new/', //,
    whatsappApiUrl: 'https://stage.eks.tiledesk.com/api/modules/whatsapp',
    // promoBannerUrl: "https://dashbordpromobanner.tiledesk.repl.co/get/dashboard_promo.json",
    chatStoragePrefix: "chat_sv6",
    tiledeskPhoneNumber: "390836308794",
    ticketingEmail: "email.tiledesk.com",
    aiModels: "gpt-4.1:3;gpt-4.1-mini:0.6;gpt-4.1-nano:0.16;gpt-4o:6;gpt-4o-mini:0.3;gpt-4:25;gpt-4-turbo-preview:12;gpt-3.5-turbo:0.6", //'gpt-3.5-turbo:0.6;gpt-4:25;gpt-4-turbo-preview:12;gpt-4o:6;gpt-4o-mini:0.3', // 'gpt-3.5-turbo:0.6;gpt-4:25;gpt-4-turbo-preview:12;gpt-4o:6;gpt-4o-mini:0.3;o1-preview:25;o1-mini:5',
    firebase: {
      apiKey: "AIzaSyBv6ILBL_U6VfUs_y8kqPYn-b2mYRauq1k",
      authDomain: "tiledesk-v3-prod-cf4ff.firebaseapp.com",
      databaseURL: "https://tiledesk-v3-prod-cf4ff-default-rtdb.europe-west1.firebasedatabase.app",
      projectId: "tiledesk-v3-prod-cf4ff",
      storageBucket: "tiledesk-v3-prod-cf4ff.appspot.com",
      messagingSenderId: "522823349790",
      appId: "1:522823349790:web:0d4ba710f38b586e1fa00f",
      vapidKey: "BH7R85jN8ovJ36J8BKYmfVZsIRWbUj_WXQMs8U3bDN02upqyqy2TpElVQIGMTUyOE2V7UwE11T_sy5yQHg02bjs"
  
    },
  };