 export const environment = {
     production: true,
     remoteConfig: true, 
     remoteConfigUrl: './dashboard-config.json',
     VERSION: require('../../package.json').version,
     t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-DGF:T-NAT:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-RAS:T',
     botcredendialsURL: 'CHANGE-IT',
     WIDGET_BASE_URL: 'https://widget.tiledesk.com/v6/',
     SERVER_BASE_URL: 'https://api.tiledesk.com/v2/',
     CHAT_BASE_URL: '../chat/',
     wsUrl: 'wss://eu.rtm.tiledesk.com/v2/ws/',
     chatEngine: 'mqtt',
     firebaseAuth: false,
     uploadEngine: 'native', 
     baseImageUrl: "CHANGEIT",
     pushEngine: 'none',
     logLevel: 'Info',
     templatesUrl: 'CHANGEIT',
     appsUrl: 'CHANGEIT',
     cdsBaseUrl: 'CHANGEIT',
     promoBannerUrl: 'CHANGEIT',
     chatStoragePrefix: "CHANGEIT",
     firebase: {
         apiKey: "CHANGE-IT",
         authDomain: "CHANGE-IT",
         databaseURL: "CHANGE-IT",
         projectId: "CHANGE-IT",
         storageBucket: "CHANGE-IT",
         messagingSenderId: "CHANGE-IT",
         appId: 'CHANGEIT',
         vapidKey: 'CHANGEIT'
    },
};
