export const environment = {
  production: false,
  remoteConfig: true,
  remoteConfigUrl: './dashboard-config.json',
  VERSION: require('../../package.json').version,
  t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-DGF:T-NAT:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-RAS:T',
  botcredendialsURL: 'CHANGEIT',
  WIDGET_BASE_URL: 'http://localhost:4200/',
  SERVER_BASE_URL: 'http://localhost:3000/',
  CHAT_BASE_URL: 'http://localhost:8080/',
  wsUrl: 'ws://localhost:3000/',
  chatEngine: 'mqtt',
  firebaseAuth: false,
  uploadEngine: 'native',
  baseImageUrl: 'CHANGEIT',
  pushEngine: 'none',
  logLevel: 'Info',
  communityTemplatesUrl: 'CHANGEIT',
  templatesUrl: 'CHANGEIT',
  appsUrl: 'CHANGEIT',
  cdsBaseUrl: 'CHANGEIT',
  promoBannerUrl: 'CHANGEIT',
  whatsappApiUrl: "CHANGEIT",
  ticketingEmail: "CHANGEIT",
  tiledeskPhoneNumber: "CHANGEIT",
  firebase: {
      apiKey: 'CHANGEIT',
      authDomain: 'CHANGEIT',
      databaseURL: 'CHANGEIT',
      projectId: 'CHANGEIT',
      storageBucket: 'CHANGEIT',
      messagingSenderId: 'CHANGEIT',
      appId: 'CHANGEIT',
      vapidKey: 'CHANGEIT'
  }
};