export const environment = {
    production: true,
    t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:F-ANA:F-ACT:F-TRI:F-GRO:F-DEP:F-OPH:F-MTL:F-CAR:F-V1L:F-PSA:F-MTT:F-SUP:F-LBS:F-APP:F-DEV:F-NOT:F-IPS:F-ETK:F-RAS:F-PPB:F-PET:F-MTS:F-TIL:F-DGF:F-NAT:F-HPB:F-TOW:F',
    VERSION: require('../../package.json').version,
    widgetUrl: 'https://widget.tiledesk.com/v4/launch.js',
    botcredendialsURL: 'CHANGE-IT',
    remoteConfig: true, 
    remoteConfigUrl: './dashboard-config.json',
    SERVER_BASE_URL: 'https://api.tiledesk.com/v2/',
    CHAT_BASE_URL: '../chat/',
    testsiteBaseUrl: 'https://api.tiledesk.com/v2/widgets/test/load',
    wsUrl: 'wss://eu.rtm.tiledesk.com/v2/ws/',
    chatEngine: 'mqtt',
    firebaseAuth: false,
    uploadEngine: 'native', 
    baseImageUrl: "CHANGEIT",
    pushEngine: 'none',
    logLevel: 'Info',
    templatesUrl: 'CHANGEIT',
    appsUrl: 'CHANGEIT',
    promoBannerUrl: 'CHANGEIT',
    chatStoragePrefix: "CHANGEIT",
    ticketingEmail: "CHANGEIT",
    tiledeskPhoneNumber: "CHANGEIT",
    firebase: {
        apiKey: "CHANGE-IT",
        authDomain: "CHANGE-IT",
        databaseURL: "CHANGE-IT",
        projectId: "CHANGE-IT",
        storageBucket: "CHANGE-IT",
        messagingSenderId: "CHANGE-IT",
        appId: 'CHANGEIT',
        vapidKey: 'CHANGEIT'
    },
};


