// export const environment = {
//     production: true,
//     t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-DGF:T-NAT:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-RAS:T',
//     VERSION: require('../../package.json').version,
//     widgetUrl: 'https://widget.tiledesk.com/v4/launch.js',
//     botcredendialsURL: 'CHANGE-IT',
//     remoteConfig: true, 
//     remoteConfigUrl: './dashboard-config.json',
//     SERVER_BASE_URL: 'https://api.tiledesk.com/v2/',
//     CHAT_BASE_URL: '../chat/',
//     testsiteBaseUrl: 'https://api.tiledesk.com/v2/widgets/test/load',
//     wsUrl: 'wss://eu.rtm.tiledesk.com/v2/ws/',
//     chatEngine: 'mqtt',
//     firebaseAuth: false,
//     uploadEngine: 'native', 
//     baseImageUrl: "CHANGEIT",
//     pushEngine: 'none',
//     logLevel: 'Info',
//     templatesUrl: 'CHANGEIT',
//     appsUrl: 'CHANGEIT',
//     promoBannerUrl: 'CHANGEIT',
//     chatStoragePrefix: "CHANGEIT",
//     firebase: {
//         apiKey: "CHANGE-IT",
//         authDomain: "CHANGE-IT",
//         databaseURL: "CHANGE-IT",
//         projectId: "CHANGE-IT",
//         storageBucket: "CHANGE-IT",
//         messagingSenderId: "CHANGE-IT",
//         appId: 'CHANGEIT',
//         vapidKey: 'CHANGEIT'
//     },
// };

// export const environment = { 
//     production: true,
//     t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-IPS:T-ETK:T-RAS:T-PPB:T-PET:T-MTS:T-TIL:T-DGF:T-NAT:F-HPB:T',
//     VERSION: require('../../package.json').version,
//     widgetUrl: 'https://widget.tiledesk.com/v5/launch.js',
//     botcredendialsURL: 'https://tiledesk-df-connector-prod.herokuapp.com/botcredendials/',
//     rasaBotCredentialsURL: "https://tiledesk-rasa-connector-prod.herokuapp.com/botcredendials/",
//     remoteConfig: false,
//     SERVER_BASE_URL: 'https://api.tiledesk.com/v2/',
//     CHAT_BASE_URL: 'https://console.tiledesk.com/v2/chat/',  //' https://console.tiledesk.com/v2/chat5-dev/',
//     testsiteBaseUrl: 'https://widget.tiledesk.com/v5/assets/twp/index.html', // 'https://widget.tiledesk.com/v5-dev/assets/twp/index.html',
//     wsUrl: 'wss://eu.rtm.tiledesk.com/v2/ws/',
//     globalRemoteJSSrc: "https://console.tiledesk.com/v2/scripts/script.js, https://console.tiledesk.com/v2/scripts/custom_script.js, https://console.tiledesk.com/v2/scripts/segment_script.js",
//     firebaseAuth: false,
//     uploadEngine: 'firebase',
//     baseImageUrl: 'https://api.tiledesk.com/v2/',
//     pushEngine: 'firebase',
//     chatEngine: 'firebase',
//     logLevel: 'Info',
//     communityTemplatesUrl: 'https://chatbot-templates.herokuapp.com/chatbots/public/community'
//     templatesUrl: "https://chatbot-templates.herokuapp.com/chatbots/public/templates/",
//     appsUrl: "https://tiledesk-apps.herokuapp.com/",
//     promoBannerUrl:  "https://dashbordpromobanner.tiledesk.repl.co/get/dashboard_promo.json", // "https://dashbordpromobanner.nicolan74.repl.co/get/dashboard_promo.json", 
//     chatStoragePrefix: "chat_sv5",
//     ticketingEmail: "tickets.tiledesk.com",
//     firebase: {
//         apiKey: "AIzaSyDKfdKrlD7AYcbQ-U-xxgV-b3FUQ4xt7NM",
//         authDomain: "tiledesk-prod-v2.firebaseapp.com",
//         databaseURL: "https://tiledesk-prod-v2.firebaseio.com",
//         projectId: "tiledesk-prod-v2",
//         storageBucket: "tiledesk-prod-v2.appspot.com",
//         messagingSenderId: "92907897826",
//         appId: "1:92907897826:web:f255664014a7cc14ee2fbb",
//         vapidKey: 'BLhTl-rK33_I4Avgk40T6MR9AGtgAfwDJK_sRbyBQHzIfyztLVsvrxILP6I6KgwagQCQIx-t6lgguEsSt0vULjw'
//     },
// };






// ENV PROD - MQTT _ PANEL.tiledesk
export const environment = {
    production: true,
    t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-IPS:T-ETK:T-RAS:T-PPB:T-PET:T-MTS:T-TIL:T-DGF:T-NAT:T-HPB:F-TOW:T',
    VERSION: require('../../package.json').version,
    widgetUrl: 'https://widget.tiledesk.com/v6/launch.js',
    botcredendialsURL: 'https://api.tiledesk.com/v3/modules/dialogflow/botcredendials/', //'https://tiledesk-df-connector-prod.herokuapp.com/botcredendials/',
    rasaBotCredentialsURL: "https://tiledesk-rasa-connector-prod.herokuapp.com/botcredendials/",
    remoteConfig: false,
    SERVER_BASE_URL: 'https://api.tiledesk.com/v3/',
    CHAT_BASE_URL: 'https://panel.tiledesk.com/v3/chat/', // 'http://localhost:8102/', // 'https://console.tiledesk.com/v2/chat5-dev/', // 'http://console.tiledesk.com/v2/chat/', 
    testsiteBaseUrl: 'https://widget.tiledesk.com/v6/assets/twp/index.html', // 'https://widget.tiledesk.com/v5-dev/assets/twp/index.html',
    wsUrl: "wss://eu.rtmv3.tiledesk.com/api/", // 'wss://eu.rtmv3.tiledesk.com/',
    globalRemoteJSSrc: "https://panel.tiledesk.com/v3/scripts/script.js, https://panel.tiledesk.com/v3/scripts/custom_script.js, https://panel.tiledesk.com/v3/scripts/segment_script.js",
    firebaseAuth: false,
    uploadEngine: 'native',
    baseImageUrl: 'https://eu.rtmv3.tiledesk.com/api/',
    pushEngine: 'firebase',
    chatEngine: 'mqtt',
    logLevel: 'info',
    communityTemplatesUrl: "https://chatbot-templates-app-v3.herokuapp.com/chatbots/public/community",
    templatesUrl: "https://chatbot-templates-app-v3.herokuapp.com/chatbots/public/templates",
    // appsUrl:"https://tiledesk-apps.herokuapp.com/",
    appsUrl: "https://api.tiledesk.com/v3/modules/apps/",
    // promoBannerUrl: "https://dashbordpromobanner.tiledesk.repl.co/get/dashboard_promo.json",
    chatStoragePrefix: "chat_sv6",
    tiledeskPhoneNumber: "390836308794",
    ticketingEmail: "email.tiledesk.com",
    firebase: {
        // apiKey: "AIzaSyDKfdKrlD7AYcbQ-U-xxgV-b3FUQ4xt7NM",
        // authDomain: "tiledesk-prod-v2.firebaseapp.com",
        // databaseURL: "https://tiledesk-prod-v2.firebaseio.com",
        // projectId: "tiledesk-prod-v2",
        // storageBucket: "tiledesk-prod-v2.appspot.com",
        // messagingSenderId: "92907897826",
        // appId: "1:92907897826:web:f255664014a7cc14ee2fbb",
        // vapidKey: 'BLhTl-rK33_I4Avgk40T6MR9AGtgAfwDJK_sRbyBQHzIfyztLVsvrxILP6I6KgwagQCQIx-t6lgguEsSt0vULjw',
         // new ---------------------
        apiKey: "AIzaSyBv6ILBL_U6VfUs_y8kqPYn-b2mYRauq1k",
        authDomain: "tiledesk-v3-prod-cf4ff.firebaseapp.com",
        databaseURL: "https://tiledesk-v3-prod-cf4ff-default-rtdb.europe-west1.firebasedatabase.app",
        projectId: "tiledesk-v3-prod-cf4ff",
        storageBucket: "tiledesk-v3-prod-cf4ff.appspot.com",
        messagingSenderId: "522823349790",
        appId: "1:522823349790:web:0d4ba710f38b586e1fa00f",
        vapidKey:"BH7R85jN8ovJ36J8BKYmfVZsIRWbUj_WXQMs8U3bDN02upqyqy2TpElVQIGMTUyOE2V7UwE11T_sy5yQHg02bjs"
        
    },
  };
  
  
  // ENV PROD - MQTT
  // export const environment = {
  //     production: true,
  //     t2y12PruGU9wUtEGzBJfolMIgK: 'PAY:T-ANA:T-ACT:T-TRI:T-GRO:T-DEP:T-OPH:T-MTL:T-CAR:T-V1L:T-PSA:T-MTT:T-SUP:T-LBS:T-APP:T-DEV:T-NOT:T-IPS:T-ETK:T-RAS:T-PPB:T-PET:T-MTS:T-TIL:T-DGF:T-NAT:T-HPB:F',
  //     VERSION: require('../../package.json').version,
  //     widgetUrl: 'https://widget.tiledesk.com/v6/launch.js',
  //     botcredendialsURL: 'https://tiledesk-df-connector-prod.herokuapp.com/botcredendials/',
  //     rasaBotCredentialsURL: "https://tiledesk-rasa-connector-prod.herokuapp.com/botcredendials/",
  //     remoteConfig: false, 
  //     SERVER_BASE_URL: 'https://api.tiledesk.com/v3/',
  //     CHAT_BASE_URL: 'http://console.tiledesk.com/v3/chat/', // 'http://localhost:8102/', // 'https://console.tiledesk.com/v2/chat5-dev/', // 'http://console.tiledesk.com/v2/chat/', 
  //     testsiteBaseUrl: 'https://widget.tiledesk.com/v6/assets/twp/index.html', // 'https://widget.tiledesk.com/v5-dev/assets/twp/index.html',
  //     wsUrl: "wss://eu.rtmv3.tiledesk.com/api/", // 'wss://eu.rtmv3.tiledesk.com/',
  //     globalRemoteJSSrc: "https://console.tiledesk.com/v2/dashboard/scripts/script.js, https://console.tiledesk.com/v2/dashboard/scripts/custom_script.js, https://console.tiledesk.com/v2/dashboard/scripts/segment_script.js",
  //     firebaseAuth: false,
  //     uploadEngine: 'native',
  //     baseImageUrl: ' https://eu.rtmv3.tiledesk.com/api/',
  //     pushEngine: 'firebase',
  //     chatEngine: 'mqtt',
  //     logLevel: 'info',
  //     // appsUrl: "https://tiledesk-apps.herokuapp.com/",
  //     appsUrl: "https://api.tiledesk.com/v3/modules/apps/",
  //     promoBannerUrl: "https://dashbordpromobanner.tiledesk.repl.co/get/dashboard_promo.json",
  //     chatStoragePrefix: "chat_sv6",
  //     firebase: {
  //         apiKey: "AIzaSyDKfdKrlD7AYcbQ-U-xxgV-b3FUQ4xt7NM",
  //         authDomain: "tiledesk-prod-v2.firebaseapp.com",
  //         databaseURL: "https://tiledesk-prod-v2.firebaseio.com",
  //         projectId: "tiledesk-prod-v2",
  //         storageBucket: "tiledesk-prod-v2.appspot.com",
  //         messagingSenderId: "92907897826",
  //         appId: "1:92907897826:web:f255664014a7cc14ee2fbb",
  //         vapidKey: 'BLhTl-rK33_I4Avgk40T6MR9AGtgAfwDJK_sRbyBQHzIfyztLVsvrxILP6I6KgwagQCQIx-t6lgguEsSt0vULjw'
  //     },
  //   };
  