import { Component, Inject, OnInit, OnDestroy, ViewChild, ElementRef, AfterViewChecked, AfterViewInit, HostListener } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import localeIt from '@angular/common/locales/it';
registerLocaleData(localeIt);
import { MAT_DIALOG_DATA, MatDialogRef } from '@angular/material/dialog';
import { NavigationStart, Router } from '@angular/router';
import { Observable, Subject } from 'rxjs';
import { takeUntil, filter, tap } from 'rxjs/operators';
import { TranslateService } from '@ngx-translate/core';
import { LoggerService } from 'app/services/logger/logger.service';
import { OpenaiService } from 'app/services/openai.service';
import { KnowledgeBaseService } from 'app/services/knowledge-base.service';
import { AppConfigService } from 'app/services/app-config.service';
import { LocalDbService } from 'app/services/users-local-db.service';
import {
  loadTokenMultiplier,
  URL_AI_model_doc,
  URL_max_tokens_doc,
  URL_temperature_doc,
  URL_chunk_Limit_doc,
  URL_system_context_doc,
  URL_advanced_context_doc,
  URL_contents_sources_doc,
} from 'app/utils/util';

type Tab = 'ai' | 'sys' | 'srcs';

interface ChatMessage {
  role: 'user' | 'bot';
  text: string;
  chunks?: string[];
  source?: string;
  source_url?: string;
  ai_model?: string;
  error?: boolean;
  busy?: boolean;
  startedAt?: number;
  durationSec?: number;
  promptTokens?: number;
}

@Component({
  selector: 'modal-preview-kb-fullscreen',
  templateUrl: './modal-preview-kb-fullscreen.component.html',
  styleUrls: ['./modal-preview-kb-fullscreen.component.scss'],
})
export class ModalPreviewKbFullscreenComponent implements OnInit, OnDestroy, AfterViewInit, AfterViewChecked {

  @ViewChild('streamEl') streamEl: ElementRef<HTMLDivElement>;
  @ViewChild('inputEl') inputEl: ElementRef<HTMLTextAreaElement>;

  private destroy$ = new Subject<void>();

  tab: Tab = 'ai';
  selectedNamespace: any;
  namespaceId: string;

  // settings (mirror preview_settings)
  selectedModel: string;
  maxTokens: number;
  temperature: number;
  topK: number;
  alpha: number;
  context: string;
  advancedPrompt = false;
  citations = true;
  chunkOnly = false;
  reRanking = false;
  reRankingMultipler: number;
  hyde = false;
  useCache = false;
  llm: string;

  // UI state
  messages: ChatMessage[] = [];
  composerText = '';
  busy = false;
  hasStreamScroll = false;

  // Tag filter (sopra il composer) e streaming (tab Sistema)
  tags: string[] = [];
  tagInput = '';
  streaming = true;

  // Save / reset UX state — tracked separately so each button shows its own spinner / result.
  saveStatus: 'idle' | 'saving' | 'success' | 'error' = 'idle';
  resetStatus: 'idle' | 'saving' | 'success' | 'error' = 'idle';
  private saveStatusResetTimer: any;
  private resetStatusResetTimer: any;
  get operationInProgress(): boolean {
    return this.saveStatus === 'saving' || this.resetStatus === 'saving';
  }

  // models list (built from app config)
  modelsList: { name: string; value: string }[] = [];

  // KB picker / sources
  namespaces: any[] = [];
  showKbPicker = false;
  sourcesByType: { type: string; labelKey: string; icon: string; count: number; items: { name: string; url?: string }[]; expanded: boolean }[] = [];
  sourcesTotal = 0;
  sourcesLoading = false;

  get numberLocale(): string {
    const lang = (this.translate.currentLang || this.translate.defaultLang || 'en').toLowerCase();
    return lang.startsWith('it') ? 'it' : 'en';
  }

  // info popover content — `text` is an i18n key resolved via the translate pipe in the template
  infos = {
    model:      { text: 'KbPage.Preview2.InfoModel',       url: URL_AI_model_doc },
    tokens:     { text: 'KbPage.Preview2.InfoTokens',      url: URL_max_tokens_doc },
    temperature:{ text: 'KbPage.Preview2.InfoTemperature', url: URL_temperature_doc },
    chunks:     { text: 'KbPage.Preview2.InfoChunks',      url: URL_chunk_Limit_doc },
    system:     { text: 'KbPage.Preview2.InfoSystem',      url: URL_system_context_doc },
    advCtx:     { text: 'KbPage.Preview2.InfoAdvCtx',      url: URL_advanced_context_doc },
    sources:    { text: 'KbPage.Preview2.InfoSources',     url: URL_contents_sources_doc },
    chunksOnly: { text: 'KbPage.Preview2.InfoChunksOnly',  url: URL_chunk_Limit_doc },
    streaming:  { text: 'KbPage.Preview2.InfoStreaming',   url: URL_system_context_doc },
    chatTags:   { text: 'KbPage.Preview2.InfoChatTags',    url: URL_contents_sources_doc },
    reRanking:  { text: 'KbPage.Preview2.InfoReRanking',   url: URL_advanced_context_doc },
    reRankMul:  { text: 'KbPage.Preview2.InfoReRankingMultiplier', url: URL_advanced_context_doc },
    hyde:       { text: 'KbPage.Preview2.InfoHyDE',        url: URL_advanced_context_doc },
    useCache:   { text: 'KbPage.Preview2.InfoUseCache',    url: URL_system_context_doc },
  };

  /**
   * Dynamic suggestions generated by the LLM on modal open.
   * Empty array → suggestion grid is hidden (no fallback to static i18n).
   */
  dynamicSuggestions: string[] = [];
  loadingSuggestions = false;

  constructor(
    @Inject(MAT_DIALOG_DATA) public data: any,
    public dialogRef: MatDialogRef<ModalPreviewKbFullscreenComponent>,
    private logger: LoggerService,
    private translate: TranslateService,
    private openaiService: OpenaiService,
    private kbService: KnowledgeBaseService,
    private appConfigService: AppConfigService,
    private localDbService: LocalDbService,
    private router: Router,
  ) {
    this.namespaces = Array.isArray(data?.namespaces) ? data.namespaces : [];
    if (data && data.selectedNamespace) {
      this.selectedNamespace = data.selectedNamespace;
      this.namespaceId = this.selectedNamespace.id;
      const s = this.selectedNamespace.preview_settings || {};
      this.selectedModel = s.model;
      this.maxTokens = s.max_tokens ?? 4096;
      this.temperature = s.temperature ?? 0.7;
      this.topK = s.top_k ?? 4;
      this.alpha = s.alpha ?? 0.5;
      this.context = s.context ?? 'You are an awesome assistant';
      this.advancedPrompt = !!s.advancedPrompt;
      this.citations = s.citations !== false;
      this.chunkOnly = !!s.chunks_only;
      this.reRanking = !!s.reranking;
      this.reRankingMultipler = s.reranking_multiplier ?? 2;
      this.hyde = !!s.hyde;
      this.useCache = !!s.use_cache;
      this.llm = s.llm;
    }
    this.buildModelsList();
  }

  ngOnInit(): void {
    // restore last question if present
    const stored = this.localDbService.getFromStorage(`last_question-${this.namespaceId}`);
    if (stored) {
      try {
        const parsed = JSON.parse(stored);
        if (typeof parsed === 'string') this.composerText = parsed;
      } catch { /* ignore */ }
    }

    // Close the modal as soon as the user navigates to another page
    this.router.events
      .pipe(filter(e => e instanceof NavigationStart), takeUntil(this.destroy$))
      .subscribe(() => this.dialogRef.close());

    // Fire-and-forget LLM request to populate the 4 example questions.
    this.loadDynamicSuggestions();
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  ngAfterViewInit(): void {
    // Focus the composer textarea AFTER MatDialog's own autoFocus runs.
    // Material focuses the first tabbable element on its `afterOpened` event,
    // so we hook into it to put focus on the chat input instead.
    this.dialogRef.afterOpened().pipe(takeUntil(this.destroy$)).subscribe(() => {
      // requestAnimationFrame + microtask delay defeats any focus trap re-grab.
      requestAnimationFrame(() => {
        setTimeout(() => this.inputEl?.nativeElement?.focus(), 0);
      });
    });
  }

  ngAfterViewChecked(): void {
    if (this.hasStreamScroll && this.streamEl) {
      this.streamEl.nativeElement.scrollTop = this.streamEl.nativeElement.scrollHeight;
      this.hasStreamScroll = false;
    }
  }

  @HostListener('document:keydown.escape')
  onEsc() { this.close(); }

  private buildModelsList() {
    try {
      const cfg = this.appConfigService.getConfig();
      const raw = cfg?.aiModels as string;
      if (raw) {
        const parsed = loadTokenMultiplier(raw) as Record<string, number>;
        this.modelsList = Object.keys(parsed || {}).map((key) => ({ name: key, value: key }));
      }
    } catch (e) {
      this.logger.log('[PREVIEW-KB-FS] buildModelsList error', e);
    }
    if (!this.modelsList.length) {
      this.modelsList = [{ name: this.selectedModel || 'gpt-4o-mini', value: this.selectedModel || 'gpt-4o-mini' }];
    }
    this.ensureCurrentModelInList();
  }

  /**
   * If the namespace's stored model is not in the global app-config list,
   * surface it as a list option so the <select> can render its label.
   * Also picks a sensible default when no model is configured.
   */
  private ensureCurrentModelInList() {
    if (!this.selectedModel) {
      this.selectedModel = this.modelsList[0]?.value;
      return;
    }
    if (!this.modelsList.some((m) => m.value === this.selectedModel)) {
      this.modelsList = [{ name: this.selectedModel, value: this.selectedModel }, ...this.modelsList];
    }
  }

  setTab(t: Tab) {
    this.tab = t;
    if (t === 'srcs' && this.sourcesByType.length === 0 && !this.sourcesLoading) {
      this.loadSources();
    }
  }
  pickModel(v: string) { this.selectedModel = v; }

  // ---- KB picker ----
  toggleKbPicker(force?: boolean) {
    this.showKbPicker = force ?? !this.showKbPicker;
  }

  selectNamespace(ns: any) {
    this.showKbPicker = false;
    if (!ns || ns.id === this.namespaceId) return;
    this.selectedNamespace = ns;
    this.namespaceId = ns.id;
    const s = ns.preview_settings || {};
    // Take the new namespace settings (fall back to sane defaults instead of keeping the previous KB's values).
    this.selectedModel = s.model || this.modelsList[0]?.value || 'gpt-4o-mini';
    this.maxTokens = s.max_tokens ?? 4096;
    this.temperature = s.temperature ?? 0.7;
    this.topK = s.top_k ?? 4;
    this.alpha = s.alpha ?? 0.5;
    this.context = s.context ?? 'You are an awesome assistant';
    this.advancedPrompt = !!s.advancedPrompt;
    this.citations = s.citations !== false;
    this.chunkOnly = !!s.chunks_only;
    this.reRanking = !!s.reranking;
    this.reRankingMultipler = s.reranking_multiplier ?? 2;
    this.hyde = !!s.hyde;
    this.useCache = !!s.use_cache;
    this.llm = s.llm;
    // Make sure the engine <select> can render the namespace's model even if it's not in the global app-config list.
    this.ensureCurrentModelInList();
    // Reset session and reload sources for the new namespace
    this.messages = [];
    this.sourcesByType = [];
    this.sourcesTotal = 0;
    this.dynamicSuggestions = [];
    this.loadDynamicSuggestions();
    if (this.tab === 'srcs') this.loadSources();
  }

  initialOf(name: string): string {
    return (name || 'K').trim().charAt(0).toUpperCase();
  }

  // ---- Sources summary ----
  private loadSources() {
    if (!this.namespaceId) return;
    this.sourcesLoading = true;
    const params = `?namespace=${this.namespaceId}&limit=1000&page=0`;
    this.kbService.getListOfKb(params).subscribe(
      (res: any) => {
        const items: any[] = Array.isArray(res?.kbs) ? res.kbs : (Array.isArray(res) ? res : []);
        this.sourcesTotal = typeof res?.count === 'number' ? res.count : items.length;
        this.sourcesByType = this.aggregateByType(items);
        this.sourcesLoading = false;
      },
      (err) => {
        this.logger.log('[PREVIEW-KB-FS] loadSources error', err);
        this.sourcesLoading = false;
      },
    );
  }

  private aggregateByType(items: any[]) {
    const meta: Record<string, { labelKey: string; icon: string; order: number }> = {
      url:    { labelKey: 'KbPage.Preview2.SrcUrl',     icon: 'link', order: 1 },
      urls:   { labelKey: 'KbPage.Preview2.SrcUrl',     icon: 'link', order: 1 },
      sitemap:{ labelKey: 'KbPage.Preview2.SrcSitemap', icon: 'link', order: 2 },
      pdf:    { labelKey: 'KbPage.Preview2.SrcPdf',     icon: 'pdf',  order: 3 },
      docx:   { labelKey: 'KbPage.Preview2.SrcDocx',    icon: 'pdf',  order: 4 },
      doc:    { labelKey: 'KbPage.Preview2.SrcDoc',     icon: 'pdf',  order: 4 },
      txt:    { labelKey: 'KbPage.Preview2.SrcTxt',     icon: 'book', order: 5 },
      text:   { labelKey: 'KbPage.Preview2.SrcTxt',     icon: 'book', order: 5 },
      faq:    { labelKey: 'KbPage.Preview2.SrcFaq',     icon: 'faq',  order: 6 },
      faqs:   { labelKey: 'KbPage.Preview2.SrcFaq',     icon: 'faq',  order: 6 },
      other:  { labelKey: 'KbPage.Preview2.SrcOther',   icon: 'doc',  order: 99 },
    };
    const groups = new Map<string, { type: string; labelKey: string; icon: string; count: number; order: number; items: { name: string; url?: string }[]; expanded: boolean }>();
    for (const it of items) {
      const key = (it?.type || 'other').toLowerCase();
      const m = meta[key] || meta['other'];
      let g = groups.get(m.labelKey);
      if (!g) {
        g = { type: key, labelKey: m.labelKey, icon: m.icon, count: 0, order: m.order, items: [], expanded: false };
        groups.set(m.labelKey, g);
      }
      g.count += 1;
      const displayName = this.deriveItemName(it);
      g.items.push({ name: displayName, url: it?.source || it?.url });
    }
    return Array.from(groups.values()).sort((a, b) => a.order - b.order);
  }

  private deriveItemName(it: any): string {
    if (it?.name && String(it.name).trim()) return String(it.name).trim();
    const src = it?.source || it?.url || it?.content;
    if (src) {
      // For URLs: strip protocol and trailing slash, keep host + path
      const str = String(src);
      if (/^https?:\/\//i.test(str)) {
        try {
          const u = new URL(str);
          const path = u.pathname.replace(/\/$/, '');
          return u.host + (path && path !== '/' ? path : '');
        } catch { /* ignore */ }
      }
      return str.length > 80 ? str.slice(0, 80) + '…' : str;
    }
    return it?._id || this.translate.instant('KbPage.Preview2.UnnamedItem');
  }

  toggleSourceGroup(g: any) {
    g.expanded = !g.expanded;
  }

  onInputKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      this.send();
    }
  }

  /**
   * Resize the composer textarea to fit its content, up to a maximum of 10 lines.
   * When the content exceeds 10 lines, a vertical scrollbar appears.
   */
  autosizeComposer(el: HTMLTextAreaElement) {
    if (!el) return;
    const style = window.getComputedStyle(el);
    const lineHeight = parseFloat(style.lineHeight) || (parseFloat(style.fontSize) * 1.5);
    const paddingY = parseFloat(style.paddingTop) + parseFloat(style.paddingBottom);
    const borderY = parseFloat(style.borderTopWidth) + parseFloat(style.borderBottomWidth);
    const maxHeight = Math.round(lineHeight * 10 + paddingY + borderY);

    el.style.height = 'auto';
    const target = Math.min(el.scrollHeight, maxHeight);
    el.style.height = target + 'px';
    el.style.overflowY = el.scrollHeight > maxHeight ? 'auto' : 'hidden';
  }

  pickSuggestion(s: string) {
    // Dynamic suggestions are already localized natural-language strings.
    // (translate.instant returns the key unchanged when not in the dictionary, so this is safe.)
    this.composerText = this.translate.instant(s);
    this.send();
  }

  /**
   * Asks the LLM for 4 example questions tailored to the current Agent's content,
   * expecting a JSON array of strings back. Failure is silent — if no parseable
   * array comes back, `dynamicSuggestions` stays empty and the grid is hidden.
   */
  private loadDynamicSuggestions() {
    if (!this.namespaceId) return;
    this.loadingSuggestions = true;
    const lang = (this.translate.currentLang || this.translate.defaultLang || 'en').toLowerCase();
    const promptIt = `In base ai contenuti indicizzati di questo Agent, suggerisci 4 domande di esempio che un utente potrebbe fargli per testarne le risposte.`;
    const promptEn = `Based on the indexed content of this Agent, suggest 4 example questions a user could ask to test its responses.`;
    const prompt = lang.startsWith('it') ? promptIt : promptEn;

    const body = {
      question: prompt,
      namespace: this.namespaceId,
      model: this.selectedModel,
      temperature: 0.7,
      alpha: this.alpha,
      max_tokens: 400,
      top_k: this.topK,
      chunks_only: false,
      reranking: false,
      reranking_multiplier: this.reRankingMultipler,
      hyde: false,
      use_cache: false,
      system_context: '',
      advancedPrompt: false,
      citations: false,
      llm: this.llm,
      tags: [],
    };

    this.openaiService.askGpt(body).pipe(takeUntil(this.destroy$)).subscribe(
      (response: any) => {
        const parsed = this.parseSuggestionsJson(response?.answer);
        this.dynamicSuggestions = parsed.slice(0, 4);
        this.loadingSuggestions = false;
      },
      (err: any) => {
        this.logger.log('[PREVIEW-KB-FS] loadDynamicSuggestions error', err);
        this.dynamicSuggestions = [];
        this.loadingSuggestions = false;
      },
    );
  }

  /**
   * Best-effort extractor for the 4 questions returned by the LLM. Tries, in order:
   *   1. JSON array (with or without Markdown fences) — most reliable
   *   2. Numbered list ("1. ...", "1) ...")
   *   3. Bulleted list ("- ...", "* ...", "• ...")
   *   4. Any non-empty lines ending with "?"
   * Returns [] if nothing usable is found.
   */
  private parseSuggestionsJson(raw: string): string[] {
    if (!raw) return [];
    const s = String(raw).trim();

    // (1) JSON array fast path
    const fenced = s.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
    const start = fenced.indexOf('[');
    const end = fenced.lastIndexOf(']');
    if (start !== -1 && end !== -1 && end > start) {
      try {
        const parsed = JSON.parse(fenced.slice(start, end + 1));
        if (Array.isArray(parsed)) {
          const strings = parsed.filter((x) => typeof x === 'string' && x.trim().length > 0).map((x) => String(x).trim());
          if (strings.length > 0) return strings;
        }
      } catch { /* fall through to text parsing */ }
    }

    // Normalize to lines and strip Markdown emphasis/quotes around each
    const lines = s
      .split(/\r?\n+/)
      .map((l) => l.trim())
      .filter(Boolean);

    const cleanItem = (text: string): string => {
      // Strip leading bullet/number markers
      let t = text.replace(/^\s*(?:\d+[.)\]:]\s*|[-*•]\s+)/, '');
      // Strip wrapping quotes
      t = t.replace(/^["“'`]+|["”'`]+$/g, '');
      // Strip surrounding markdown bold/italics
      t = t.replace(/^\*\*([^*]+)\*\*$/, '$1').replace(/^_([^_]+)_$/, '$1');
      return t.trim();
    };

    // (2) Numbered list
    const numbered = lines
      .filter((l) => /^\d+[.)\]:]\s+\S/.test(l))
      .map(cleanItem)
      .filter((x) => x.length > 0);
    if (numbered.length > 0) return numbered;

    // (3) Bulleted list
    const bulleted = lines
      .filter((l) => /^[-*•]\s+\S/.test(l))
      .map(cleanItem)
      .filter((x) => x.length > 0);
    if (bulleted.length > 0) return bulleted;

    // (4) Any line ending with "?" — last resort
    const questions = lines
      .map(cleanItem)
      .filter((x) => x.endsWith('?') && x.length > 2);
    return questions;
  }

  // ---- Tag filter ----
  addTagFromInput() {
    const t = (this.tagInput || '').trim();
    if (!t) return;
    if (!this.tags.includes(t)) this.tags.push(t);
    this.tagInput = '';
  }
  removeTag(idx: number) {
    this.tags.splice(idx, 1);
  }
  onTagKeydown(e: KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      this.addTagFromInput();
    } else if (e.key === 'Backspace' && !this.tagInput && this.tags.length > 0) {
      this.tags.pop();
    }
  }

  resetSession() {
    this.messages = [];
  }

  /**
   * Reset all AI settings to the same default values used by the legacy
   * ModalPreviewSettingsComponent.resetToDefault() and persist them — feedback
   * (spinner / success / error) shows on the Reset button, not on Save.
   */
  resetSettings() {
    if (this.operationInProgress) return;
    // Defaults mirror modal-preview-settings.component.ts (legacy)
    this.selectedModel = 'gpt-4o';
    this.maxTokens = 256;
    this.temperature = 0.7;
    this.alpha = 0.5;
    this.topK = 4;
    this.context = '';
    this.advancedPrompt = false;
    this.citations = false;
    this.chunkOnly = false;
    this.reRanking = false;
    this.reRankingMultipler = 2;
    this.hyde = false;
    this.useCache = false;
    this.streaming = true;
    this.ensureCurrentModelInList();
    if (!this.namespaceId) { this.flagReset('error'); return; }
    this.flagReset('saving');
    this.persistPreviewSettings().subscribe(
      () => this.flagReset('success'),
      (err: any) => { this.logger.log('[PREVIEW-KB-FS] resetSettings error', err); this.flagReset('error'); },
    );
  }

  saveSettings() {
    if (this.operationInProgress) return;
    if (!this.namespaceId) { this.flagSave('error'); return; }
    this.flagSave('saving');
    this.persistPreviewSettings().subscribe(
      () => this.flagSave('success'),
      (err: any) => { this.logger.log('[PREVIEW-KB-FS] saveSettings error', err); this.flagSave('error'); },
    );
  }

  /**
   * Builds the preview_settings body from current local state and PUTs it
   * to the backend. Also updates `selectedNamespace.preview_settings` on success
   * so subsequent reads see the persisted snapshot.
   */
  private persistPreviewSettings(): Observable<any> {
    const previewSettings = {
      ...(this.selectedNamespace.preview_settings || {}),
      model: this.selectedModel,
      max_tokens: this.maxTokens,
      temperature: this.temperature,
      top_k: this.topK,
      context: this.context,
      advancedPrompt: this.advancedPrompt,
      citations: this.citations,
      chunks_only: this.chunkOnly,
      reranking: this.reRanking,
      reranking_multiplier: this.reRankingMultipler,
      hyde: this.hyde,
      use_cache: this.useCache,
    };
    const body = { preview_settings: previewSettings } as any;
    return this.kbService.updateNamespace(body, this.namespaceId).pipe(
      tap(() => {
        this.selectedNamespace = { ...this.selectedNamespace, preview_settings: previewSettings };
      }),
    );
  }

  private flagSave(s: 'idle' | 'saving' | 'success' | 'error') {
    this.saveStatus = s;
    if (this.saveStatusResetTimer) { clearTimeout(this.saveStatusResetTimer); this.saveStatusResetTimer = null; }
    if (s === 'success' || s === 'error') {
      this.saveStatusResetTimer = setTimeout(() => { this.saveStatus = 'idle'; }, 2500);
    }
  }

  private flagReset(s: 'idle' | 'saving' | 'success' | 'error') {
    this.resetStatus = s;
    if (this.resetStatusResetTimer) { clearTimeout(this.resetStatusResetTimer); this.resetStatusResetTimer = null; }
    if (s === 'success' || s === 'error') {
      this.resetStatusResetTimer = setTimeout(() => { this.resetStatus = 'idle'; }, 2500);
    }
  }

  send() {
    const text = (this.composerText || '').trim();
    if (!text || this.busy) return;

    this.messages.push({ role: 'user', text });
    this.composerText = '';
    if (this.inputEl?.nativeElement) {
      // reset textarea height after send
      requestAnimationFrame(() => this.autosizeComposer(this.inputEl.nativeElement));
    }
    this.busy = true;
    this.hasStreamScroll = true;

    if (text) {
      this.localDbService.setInStorage(`last_question-${this.namespaceId}`, JSON.stringify(text));
    }

    // include any tag still in the input as a finalized tag
    this.addTagFromInput();

    const body = {
      question: text,
      namespace: this.namespaceId,
      model: this.selectedModel,
      temperature: this.temperature,
      alpha: this.alpha,
      max_tokens: this.maxTokens,
      top_k: this.topK,
      chunks_only: this.chunkOnly,
      reranking: this.reRanking,
      reranking_multiplier: this.reRankingMultipler,
      hyde: this.hyde,
      use_cache: this.useCache,
      system_context: this.context,
      advancedPrompt: this.advancedPrompt,
      citations: this.citations,
      llm: this.llm,
      tags: [...this.tags],
    };

    const placeholder: ChatMessage = { role: 'bot', text: '', busy: true, startedAt: performance.now() };
    this.messages.push(placeholder);

    const onError = (err: any) => {
      placeholder.busy = false;
      placeholder.error = true;
      placeholder.text = this.extractError(err);
      this.busy = false;
      this.hasStreamScroll = true;
    };
    const finalizeFromResponse = (response: any) => {
      placeholder.busy = false;
      placeholder.text = response?.answer || placeholder.text || this.translate.instant('KbPage.NoAnswerFound');
      placeholder.chunks = response?.content_chunks || placeholder.chunks || [];
      placeholder.source = response?.source;
      placeholder.ai_model = this.selectedModel;
      if (response?.source && /^(https?|ftp):\/\//.test(response.source)) {
        placeholder.source_url = response.source;
      }
      // Response time: prefer backend value if present, else compute locally
      const backendDuration = typeof response?.duration === 'number' ? response.duration : undefined;
      if (backendDuration !== undefined) {
        // backend may return ms or s — heuristic: if > 100, assume ms
        placeholder.durationSec = backendDuration > 100 ? backendDuration / 1000 : backendDuration;
      } else if (placeholder.startedAt) {
        placeholder.durationSec = (performance.now() - placeholder.startedAt) / 1000;
      }
      // Prompt size in tokens
      const tokens = response?.prompt_token_size ?? response?.usage?.prompt_tokens;
      if (typeof tokens === 'number') placeholder.promptTokens = tokens;

      this.busy = false;
      this.hasStreamScroll = true;
    };

    if (this.streaming) {
      this.openaiService.askGptStream(body).subscribe(
        (evt: any) => {
          if (evt?.done) { finalizeFromResponse(evt.response || {}); return; }
          if (evt?.fullAnswer !== undefined) {
            placeholder.busy = false;
            placeholder.text = evt.fullAnswer;
          } else if (evt?.text) {
            placeholder.busy = false;
            placeholder.text = (placeholder.text || '') + evt.text;
          }
          this.hasStreamScroll = true;
        },
        onError,
      );
    } else {
      this.openaiService.askGpt(body).subscribe(finalizeFromResponse, onError);
    }
  }

  private extractError(err: any): string {
    // Try to drill into the most informative field of the response body.
    // Backend payloads we've seen:
    //   { error: { message, name }, success: false }
    //   { error: { answer, error_message }, success: false }
    //   { message: "..." }
    //   { error_message: "BadRequestError(...'message': '...')" }
    const e = err?.error;
    let raw: string | undefined;

    if (typeof e === 'string') raw = e;
    else if (e?.error?.message) raw = e.error.message;
    else if (e?.error?.answer) raw = e.error.answer;
    else if (e?.error_message) {
      const m = String(e.error_message).match(/'message':\s*'([^']+)'/);
      raw = m ? m[1] : e.error_message;
    }
    else if (e?.message) raw = e.message;
    else if (err?.message && !/^Http failure/i.test(err.message)) raw = err.message;

    // Friendly translation for common network failures
    if (raw && /ECONNREFUSED|ETIMEDOUT|ENOTFOUND|EAI_AGAIN/i.test(raw)) {
      return this.translate.instant('KbPage.Preview2.ErrAINotReachable');
    }

    if (raw) return raw;

    // Fallback with status context
    const status = err?.status;
    if (status === 0)   return this.translate.instant('KbPage.Preview2.ErrNetwork');
    if (status === 401) return this.translate.instant('KbPage.Preview2.ErrSessionExpired');
    if (status === 403) return this.translate.instant('KbPage.Preview2.ErrForbidden');
    if (status === 404) return this.translate.instant('KbPage.Preview2.ErrNotFound');
    if (status >= 500)  return this.translate.instant('KbPage.Preview2.ErrServer', { status });

    return this.translate.instant('KbPage.Preview2.ErrGeneric');
  }

  // ---- Info popover hover handling: keep open while moving across the gap to the popover ----
  private closeTimers = new Map<any, any>();
  openInfo(ref: any) {
    const t = this.closeTimers.get(ref);
    if (t) { clearTimeout(t); this.closeTimers.delete(ref); }
    ref?.open?.();
  }
  scheduleCloseInfo(ref: any) {
    const t = setTimeout(() => { ref?.close?.(); this.closeTimers.delete(ref); }, 200);
    this.closeTimers.set(ref, t);
  }
  cancelCloseInfo(ref: any) {
    const t = this.closeTimers.get(ref);
    if (t) { clearTimeout(t); this.closeTimers.delete(ref); }
  }

  copyToClipboard(text: string) {
    try { navigator.clipboard?.writeText(text); } catch { /* noop */ }
  }

  close() {
    this.dialogRef.close();
  }
}
